### ISSUE TITLE
Update to CoffeeScript v1.9.3

### ISSUE THREAD

**Issue by madskristensen** [tomlokhorst/CoffeeSharp#16]
First of all, thanks for an awesome product. I've started using it in my latest Visual Studio extension https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c and it rocks!!

Is there a chance to get support for the latest CoffeeScript compiler version 1.9.3?

**Comment by tomlokhorst** [comment]
Hey! I didn't know anyone was still using this, let alone for a new project. To be honest, I've not used it myself for years (which is why it's still at CoffeeScript version 1.3.1).

I'll have a look to see if I can update it. It involves resurrecting an old VM, so it it's a bit of work.

Out of curiosity; Have you looked at other methods of compiling CoffeeScript? I'm surprised that this old project is the one you like best. How did CoffeeScript compilation work for Web Essentials?

**Comment by madskristensen** [comment]
I've compiled using Windows Script Host and Node.js earlier. Web Essentials uses node.js.

So far, your project has been the easiest to work with. Spinning up a node.js server adds complexity and more moving parts that can (and will) fail. Would you recommend a different approach?

**Comment by tomlokhorst** [comment]
I don't have a better approach at the moment. And if it works, it works!

I've update the nuget package to CoffeeScript 1.9.3: http://www.nuget.org/packages/CoffeeSharp/
The small stuff I tried it on seems to work. Do let me know if something is broken.
